const catalogo = [
    {id: 1, name: 'Guitarra electrica Alabama TL-201', price: 720, description: 'Guitarra electrica Alabama para diestros, para todo tipo de amplificadores y generos', category: 'guitar', pictureURL: '../img/products/guitarAlabamaTL201.png'}, 
    {id: 2, name: 'Guitarra electrica Les Paul SX EE3 SERIES', price: 600, description: 'Guitarra electrica Les Paul SX EE3 SERIES de muy buena calidad, prefentenmente para genero rock y pop', category: 'guitar', pictureURL: 'https://http2.mlstatic.com/D_NQ_NP_898146-MLA31579260003_072019-O.jpg'},
    {id: 3, name: 'Guitarra electrica Les Paul Epiphone Special VE', price: 580, description: 'Guitarra electrica Les Paul Epiphone Special VE, de buena gama intermedia, ideal para comenzar a tocar en bandas', category: 'guitar', pictureURL: 'https://http2.mlstatic.com/D_NQ_NP_660319-MLA43545062717_092020-O.webp'},
    {id: 4, name: 'Paiste 101 Crash Ride 18 Pulgadas', price: 110, description: 'Crash Ride de 18 pulgadas del set 101 de Paiste, un muy buen platillo para comenzar a tocar, muy flexible, sonido armonioso', category:'drum', pictureURL: 'https://http2.mlstatic.com/D_NQ_NP_955165-MLA31063898160_062019-O.webp'}, 
    {id: 5, name: 'Paiste 101 Hi Hat 14 Pulgadas', price: 140, description: 'Hi-Hat de 14 pulgadas del set 101 de Paiste, gran juego de platos para comenzar a tocar, sonido armonioso', category:'drum', pictureURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmhF6xDrCN8T5NKdM_N2S3Sq0WM4VL0hYXQTX3DgfsimrOou7ODphtbizYNhBtvBvxT5k&usqp=CAU'},
    {id: 6, name: 'Soporte Mapex Jirafa Boom', price: 70, description: 'Soporte Mapex Boom hasta platos de 20 pulgadas, consultar por set completo', category:'drum', pictureURL: 'https://http2.mlstatic.com/D_NQ_NP_796796-MLA31017111008_062019-O.webp'},
    {id: 7, name: 'Teclado Roland Go-61kl 61 Sintetizador', price: 880, description: 'Teclado y sintetizador Roland, de muy buena calidad, para avanzados que buscan flexibilidad y buen sonido para tocar en vivo', category:'key', pictureURL: 'https://http2.mlstatic.com/D_NQ_NP_927391-MLA45374340759_032021-O.webp'}, 
    {id: 8, name: 'Fuente Para Teclado Casio Modelo 7,5v', price: 5, description: 'Fuente adaptable para todo tipo de teclados e instrumentos varios. Hasta 7,5v', category:'key', pictureURL: 'https://http2.mlstatic.com/D_NQ_NP_690896-MLA41147203406_032020-O.webp'},
    {id: 9, name: 'Encordado Jazz Fender Guitarra Electrica 013 56 250jm', price: 10, description: 'Encordado para jazz de fender, juego de 7 cuerdas (set de 6 con una mas gruesa de regalo)', category:'guitar', pictureURL: 'https://http2.mlstatic.com/D_NQ_NP_868789-MLA48067330974_102021-O.webp'},
    {id: 10, name: 'Guitarra criolla clásica Yamaha C80', price: 610, description: 'Gran guitarra criolla marca Yamaha, para aficionados que buscan un sonido armonioso y elegante', category:'guitar', pictureURL: 'https://http2.mlstatic.com/D_NQ_NP_634463-MLA46245880276_062021-O.webp'}, 
    {id: 11, name: 'Bateria Acústica Parquer 5 Cuerpos Negra Platillos Soporte', price: 820, description: 'Bateria Parquer, para comenzar a tocar. Incluye platos de practica y set de 3 soportes (Hi-Hat, Crash y Ride)', category:'drum', pictureURL: 'https://http2.mlstatic.com/D_NQ_NP_935827-MLA44038834299_112020-O.webp'},
    {id: 12, name: 'Funda Para Guitarra Eléctrica Proel Bag 120pn', price: 20, description: 'Funda en oferta, 3 bolsillos, calidad premium, flexibilidad para todo tipo de guitarras, suavidad interna', category:'guitar', pictureURL: 'https://http2.mlstatic.com/D_NQ_NP_781608-MLA31011649051_062019-O.webp'},
    {id: 13, name: 'Amplificador De Guitarra Marshall Dsl 20 Cr 12 2 Canales', price: 930, description: 'Importante amplificador Marshall para profesionales o conciertos en vivo, excelente calidad de sonido, adaptable para bajos, guitarras y microfonos', category:'guitar', pictureURL: 'https://http2.mlstatic.com/D_NQ_NP_817764-MLA41229313438_032020-O.webp'},
    {id: 14, name: 'Piano De Cola Yamaha Gb1kpe', price: 13000, description: 'Increible piano de cola Yamaha Gb1kpe, interesados mandar por mensajeria privada para mas detalles de producto, medios de pago y traslado', category:'key', pictureURL: 'https://http2.mlstatic.com/D_NQ_NP_927123-MLA31597656548_072019-O.webp'}
]

export default catalogo